### ISSUE TITLE
Error 403: Limit of connected athletes exceeded

### ISSUE THREAD

**Issue by DW4y** [jat255/strava-to-fittrackee#25]
Hello,

I have everthing set like in the readme. After click "Authorize" stava shows me:

> Error 403: Limit of connected athletes exceeded
> 
> This app has exceeded the limit of connected athletes. If you are a developer of this application, please contact Strava developer support for how to request a quota increase.
> 

Even if I try the url it says:

`File "/home/pierre/.cache/pypoetry/virtualenvs/strava-to-fittrackee-JaUpv7uk-py3.10/lib/python3.10/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 284, in parse_authorization_code_response
    raise MissingCodeError("Missing code parameter in response.")
oauthlib.oauth2.rfc6749.errors.MissingCodeError: (missing_code) Missing code parameter in response.
[1]-  Exit 127                https://localhost
[3]+  Done                    scope=activity%3Aread_all
`

Thanks!

**Comment by jat255** [comment]
Hmm, I'm not sure what the issue is. You set up an API application in your settings at this page: https://www.strava.com/settings/api ?

Are you using your API application for anything that might be causing you to hit a limit of some sort? I've never seen this error before, so I'm not sure how much help I can provide.

**Comment by DW4y** [comment]
Could work it out with strava, was not a problem with your app. Sorry m8 and thanks for the good work!
